### ISSUE TITLE
Allocation of the detected fill-ins

### ISSUE THREAD

**Issue by hlakshmidevi10** [Anil-Gaihre/gSoFa#1]
Hi,

I was browsing the symbfact.cuh for without and with space optimization and realized that the fill-in detection doesn't necessarily allocate or return the filled-in matrix. Instead, I see only the fill-in count returned after the symbolic factorization.

Is my interpretation correct? 

It also seems like the code with supernodes is not compiling.  

Thanks!

**Comment by Anil-Gaihre** [comment]
Hello, 
You are right. This version of the code doesn't return the filled matrix. We are in the process of embedding the module into a direct solver with those features included.
The latest code of supernode is not made public yet and this version might have some issues. We will shortly publish them once the embedding is completed.
